// src/constants/permissions.js

export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  MANAGE_USERS: "MANAGE_USERS",

  MANAGE_ROLES: "MANAGE_ROLES",

  MANAGE_PRODUCTS: "MANAGE_PRODUCTS",

  MANAGE_STOCK: "MANAGE_STOCK",

  MANAGE_SALES: "MANAGE_SALES",

  MANAGE_PURCHASES: "MANAGE_PURCHASES",

  VIEW_REPORTS: "VIEW_REPORTS",

  MANAGE_SETTINGS: "MANAGE_SETTINGS",
};
