name: PharmaERP Bot Commit

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - development
          - uat
          - production

permissions:
  contents: write

jobs:
  bot-commit:
    name: Bot Commit - ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Set deployment configuration
        id: config
        run: |
          case "${{ inputs.environment }}" in
            development)
              echo "branch=develop" >> "$GITHUB_OUTPUT"
              echo "message=chore: deploy development by PharmaERP Bot" >> "$GITHUB_OUTPUT"
              ;;

            uat)
              echo "branch=uat" >> "$GITHUB_OUTPUT"
              echo "message=chore: deploy uat by PharmaERP Bot" >> "$GITHUB_OUTPUT"
              ;;

            production)
              echo "branch=main" >> "$GITHUB_OUTPUT"
              echo "message=chore: deploy production by PharmaERP Bot" >> "$GITHUB_OUTPUT"
              ;;
          esac

      - name: Checkout deployment branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.config.outputs.branch }}
          fetch-depth: 0

      - name: Configure PharmaERP Bot
        run: |
          git config user.name "PharmaERP Bot"
          git config user.email "pharmaerp.tech@gmail.com"

      - name: Create Bot Commit
        run: |
          git commit --allow-empty \
            -m "${{ steps.config.outputs.message }}"

      - name: Push Bot Commit
        run: |
          git push origin "${{ steps.config.outputs.branch }}"
