name: PharmaERP Bot Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bot-commit:
    name: Bot Commit - ${{ github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Set deployment configuration
        id: config
        run: |
          case "${GITHUB_REF_NAME}" in
            develop)
              echo "message=chore: deploy development by PharmaERP Bot" >> "$GITHUB_OUTPUT"
              ;;

            uat)
              echo "message=chore: deploy uat by PharmaERP Bot" >> "$GITHUB_OUTPUT"
              ;;

            main)
              echo "message=chore: deploy production by PharmaERP Bot" >> "$GITHUB_OUTPUT"
              ;;

            *)
              echo "❌ Unsupported branch: ${GITHUB_REF_NAME}"
              echo "Allowed branches: develop, uat, main"
              exit 1
              ;;
          esac

      - name: Checkout deployment branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Configure PharmaERP Bot
        run: |
          git config user.name "PharmaERP Bot"
          git config user.email "pharmaerp.tech@gmail.com"

      - name: Create Bot Commit
        run: |
          git commit --allow-empty \
            -m "${{ steps.config.outputs.message }}"

      - name: Push Bot Commit
        run: |
          git push origin "${GITHUB_REF_NAME}"
